spring.application.name=agrosat-soap-service
server.port=8082

# Oracle DataSource (mesmo banco que a REST API)
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.username=RM99856
spring.datasource.password=280105
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

logging.level.org.springframework.ws=DEBUG
logging.level.com.agrosatmonitor=INFO

# HikariCP ? evita ORA-17008
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
